### PR TITLE
optional overriding of container cmd

### LINKED ISSUE #15: Support for podman
Podman has a docker compatible CLI, so just being able to substitute docker with podman with a config or something would already solve this. A workaround is `alias docker="podman"`, so I would also understand if this is rejected.

### PR DESCRIPTION
**Pull request by jgero**
This would enable overriding the builder of the commandthat launches the container like this in your config (closes #15):

```lua
  cmd = require'lspcontainers'.command('???', {
  cmd_builder = function(volume, image)
      return {
          "podman",
          "container",
          "run",
          "--interactive",
          "--rm",
          "--volume",
          volume,
          image
        }
  end
  }),
```

If no additional config is provided it will just fall back to the default docker command.

### CODE REVIEW

**Comment by erkrnt** [comment]
I really like the idea behind this - though I need to do a little investigation on the approach. The main reason is because I have known for awhile now that `eventually` we will need a function that generates the command run in Docker, Podman, etc. I'd like to solve that first - then possible hook into that with a configuration object.

Would be interested in knowing your thoughts on this one @nogweii and @jgero?

**Comment by jgero** [comment]
I think it would make sense to expose the option of providing such a builder function not only to the user configs, but also to the default config of the plugin (so basically expanding the `supported_languages` table to also take a builder function in addition to the image name). Then we could first check if the user provided a builder function, if not try to use the builder function from the language config, if that does not exist either fall back to a default builder.

This would also enable a kind of "easy mode" for using podman, because then we could just add another `container_runtime` argument that we pass to the builder functions that defaults to "docker" but can be passed to it like this:

```
cmd = require'lspcontainers'.command('???', {
  container_runtime = "podman"
}),
```

And in our default `cmd_builder` we do something like this:

```
  function(runtime, volume, image)
      return {
          runtime,
          "container",
          "run",
          "--interactive",
          "--rm",
          "--volume",
          volume,
          image
        }
  end
```

**Comment by jgero** [comment]
Okay so I threw something together that does what I meant. There is now a default `cmd_builder` function that takes a `runtime`, `volume` and `image`. This function can be overwritten in the defaults of the plugin (if some container always needs a different command) or by the user. In addition to that the users can just provide a `container_runtime` option, which then will be passed into the default functions. That would make switching from docker to podman is as simple as this:

```lua
require'lspconfig'.sumneko_lua.setup {
    cmd = require'lspcontainers'.command('sumneko_lua', {
		container_runtime = "podman",
    }),
}
```

And if the user wants to not only overwrite the runtime, but the entire command that would work like this:

```lua
lspconfig.svelte.setup {
  cmd = require'lspcontainers'.command('svelte', {
    container_runtime = "podman",
    additional_languages = {
      svelte = {
        image = "sveltels:latest",
        cmd = function (runtime, volume, image)
          return {
            runtime,
            "container",
            "run",
            "--interactive",
            "--rm",
            "--volume",
            volume,
            image
          }
        end
      },
   }),
}
```

**Comment by erkrnt** [comment]
This looks great to me! Will go ahead and merge as this is something we definitely need and can iterate more later. Awesome work!!

**Pull request merged**
